### ISSUE TITLE
Le métronome ne démarre pas dans Firefox (ok dans Chrome)

### ISSUE THREAD

**Issue by taniamcnamara** [InnovaLangues/metronome#4]
Le métronome ne démarre pas dans Firefox (aucne réaction sur aucun bouton) sur mon PC alors qu'il démarre et fonctionne bien dans Chrome. Version firefox = 34.0.5

**Comment by pitrackster** [comment]
Testé rapidement par tous les collègues sur Firefox 34 -> 36 sur linux et windows 7 et ... ça semble marcher (le son est produit et la lumière clignote).

Peux-tu t'assurer que : 
- c'est bien le son par défaut qui est sélectionné (Woodblock)
- le bouton Sound & light est sélectionné

Sinon il faut que je vois sur ta machine ce qu'il se passe...

**Comment by pitrackster** [comment]
problème d'url obsolète
